
DROP TABLE PERSON;
CREATE TABLE PERSON(ID BIGINT AUTO_INCREMENT, FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255), EMAIL VARCHAR(255));

INSERT INTO PERSON(FIRST_NAME, LAST_NAME, EMAIL)
VALUES('Rai', 'Singh', 'rsingh@edmunds.com');

INSERT INTO PERSON(FIRST_NAME, LAST_NAME, EMAIL)
VALUES('Jane', 'Doe', 'jdoe@edmunds.com');

INSERT INTO PERSON(FIRST_NAME, LAST_NAME, EMAIL)
VALUES('Ron', 'Swanson', 'rswanson@edmunds.com');
